echo "mashable health"
python search_twitter.py mashable health > "twitter_mashable_health_$(date +%Y-%m-%d_%H:%M:%S).txt"
echo "pratikpoddar startups"
python search_twitter.py pratikpoddar startups > "twitter_pratikpoddar_startups_$(date +%Y-%m-%d_%H:%M:%S).txt"
echo "mashable non-profits"
python search_twitter.py mashable non-profits > "twitter_mashable_non-profits_$(date +%Y-%m-%d_%H:%M:%S).txt"
echo "Scobleizer tech-news-people"
python search_twitter.py Scobleizer tech-news-people > "twitter_Scobleizer_tech-news-people_$(date +%Y-%m-%d_%H:%M:%S).txt"
echo "Scobleizer weapons-for-entrepreneurs"
python search_twitter.py Scobleizer weapons-for-entrepreneurs > "twitter_Scobleizer_weapons-for-entrepreneurs_$(date +%Y-%m-%d_%H:%M:%S).txt"
echo "jasonsparrow cio"
python search_twitter.py jasonsparrow cio > "twitter_jasonsparrow_cio_$(date +%Y-%m-%d_%H:%M:%S).txt"
echo "sachin tendulkar"
python search_twitter.py "sachin tendulkar" > "twittersearch_sachin_tendulkar_$(date +%Y-%m-%d_%H:%M:%S).txt"

